# .pre-commit-config.yaml

repos:
- repo: https://github.com/psf/black
  rev: 24.10.0  # Use the latest stable version
  hooks:
    - id: black
      args: [--safe]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-docstring-first
    - id: check-added-large-files
    - id: check-toml
    - id: check-yaml
      args:
        - --unsafe
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: ["--markdown-linebreak-ext=md"]
      language_version: python3

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.4  # Update with the version from pyproject.toml
  hooks:
    - id: ruff
      args:
        - --fix
        - --extend-include=*.ipynb
        - --select=I,T201
    - id: ruff-format

- repo: https://github.com/PyCQA/flake8
  rev: 7.1.1  # Update with the version from pyproject.toml
  hooks:
    - id: flake8
      args: [--max-line-length=1000,--exclude=tests,examples,docs,logs,tests,notebooks,design,Chatbot-streamlit,.github]
      language_version: python3

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.14.0
  hooks:
    - id: reorder-python-imports
      args: [--application-directories=.explainit, --py38-plus]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.1
  hooks:
    - id: pyupgrade
      args: [--py38-plus]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.4  # Replace with the desired version of ruff
    hooks:
    -   id: ruff
        args: [--extend-include=*.ipynb, --select=E,F,I,T201]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.0  # Update with the version from pyproject.toml
  hooks:
    - id: mypy
      files: ^hybrid_rag/
      args: [--ignore-missing-imports]

# - repo: local
#    hooks:
#     - id: pytest
#       name: pytest
#       entry: ./.venv/bin/pytest tests
#       language: system
#       types: [python]
#       pass_filenames: false
#       always_run: true

-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
        args:
        - --skip
        - '.git,*.pdf,*.svg,*.yaml,*.ipynb,poetry.lock,*.min.js,*.css,package-lock.json,example_data,_dist,examples,templates,*.trig,*.csv,.dockerignore,.gitattributes,.gitignore,Dockerfile,Makefile,*.lock,*.toml,*.md,*.conf'
        - --ignore-regex
        - '.*(Stati Uniti|Tense=Pres).*'
        - --ignore-words-list
        - 'momento,collison,ned,foor,reworkd,parth,whats,aapply,mysogyny,unsecure,damon,crate,aadd,symbl,precesses,accademia,nin,cann'

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
